### ISSUE TITLE
Resume Bug

### ISSUE THREAD

**Issue by calebhuangsea** [uwIdeaFactory/IdeaFactoryFrontend#39]
If you have a resume and next time if you don't submit a resume, your previous resume will be gone

**Comment by priddhesh** [comment]
Please assign me this task.

**Comment by Kuro1Fury** [comment]
> Please assign me this task.

This issue is already fixed and would be closed soon

**Comment by calebhuangsea** [comment]
> Please assign me this task.

May I ask who you are?

**Comment by priddhesh** [comment]
I assume that you know anyone around the globe can access the open source projects.I am one among them.How is it possible for you to know anyone?
